##################################################
# Common Variables
##################################################

app:
    name: "docker-ansible-azure"

azure:
    location: "uksouth"

##################################################
# Defaults - These should be OK to leave as is
##################################################

# Dictionary - for affixes
##################################################
dict:
    resource_group: "rg"
